# Generated by Django 5.2.4 on 2025-07-08 08:22

import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='geo_coordinates',
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='41.3874,2.1686', max_length=63),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
