# Generated by Django 5.2.4 on 2025-07-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilm', '0002_remove_location_geo_coordinates_location_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='class_name',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('UNEXPECTED', 'Unexpected'), ('ANORMAL', 'Anormal'), ('ALERT', 'Alert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('FRIDGE', 'Fridge'), ('OVEN', 'Oven'), ('KETTLE', 'Kettle'), ('MICROWAVE', 'Microwave'), ('WASHING MACHINE', 'Washing Machine'), ('IRON', 'Iron'), ('LIGHTS', 'Lights'), ('TV', 'TV')], max_length=20),
        ),
    ]
