# Generated by Django 5.2.4 on 2026-07-19 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilm', '0005_measurement_end_time_measurement_readings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='location',
        ),
        migrations.AddField(
            model_name='measurement',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='nilm.device'),
        ),
    ]
