# Generated by Django 5.2.4 on 2026-08-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilm', '0006_remove_measurement_location_measurement_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('DOMOBOI', 'Domoboi Edge (ATM90E36)'), ('TUYA', 'Tuya Cloud Device')], default='DOMOBOI', max_length=10),
        ),
        migrations.AddField(
            model_name='measurement',
            name='features',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='telemetry',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
