"""
Django settings for domoboi_django project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Load local settings (such as SECRET_KEY and EDGE_API_TOKEN)
try:
    from .local_settings import SECRET_KEY, EDGE_API_TOKEN
except ImportError:
    # Fallback to environment variables if local_settings is not present (e.g. CI or fresh deployments)
    SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-fallback-key-change-me')
    EDGE_API_TOKEN = os.getenv('EDGE_API_TOKEN', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['suara.domoboi.es', 'localhost','192.168.1.133', '127.0.0.1']
# Application definition

UNFOLD = {
    "SITE_TITLE": _("DOMOBOI"),
    "SITE_HEADER": _("DOMOBOI"),
    "SITE_SUBHEADER": _("Administration platform"),
    "STYLES": [
        lambda request: static("css/dashboard.css"),
    ],

    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Despliegue"),
                "icon": "sports_motorsports",
                #"active": "formula.utils.driver_list_link_callback",
                "items": [
                    {
                        "title": _("Personas"),
                        "icon": "frame_person",
                        "link": reverse_lazy("admin:nilm_person_changelist"),
                        # "active": "formula.utils.driver_list_link_callback",
                    },
                    {
                        "title": _("Domicilios"),
                        "icon": "home",
                        "link": reverse_lazy("admin:nilm_location_changelist"),
                    },
                    {
                        "title": _("Dispositivos"),
                        "icon": "home",
                        "link": reverse_lazy("admin:nilm_device_changelist"),
                    },
                   
                ],
            },
            {
                "title": _("Seguimiento"),
                "icon": "sports_motorsports",
                #"active": "formula.utils.driver_list_link_callback",
                "items": [

                    {
                        "title": _("Datos"),
                        "icon": "bar_chart",
                        "link": reverse_lazy("admin:nilm_measurement_changelist"),
                    },
                    {
                        "title": _("Eventos"),
                        "icon": "event_available",
                        "link": reverse_lazy("admin:nilm_event_changelist"),
                    },
                   
                ],
            },
            {
                "title": _("Usuarios"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "account_circle",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": _("Desarrollador"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("API Docs"),
                        "icon": "article",
                        "link": "/nilm/api/docs/",
                    },
                ],
            },
        ],
    },
}

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    #"unfold.contrib.import_export",  # optional, if django-import-export package is used
    #"unfold.contrib.guardian",  # optional, if django-guardian package is used
    #"unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    #"unfold.contrib.constance",  # optional, if django-constance package is used
    #'adminlte3',
    #'adminlte3_theme',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_extensions',
    'location_field',
    'rest_framework',
    'drf_spectacular',
    'webpush',
    'nilm',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Domoboi Edge API',
    'DESCRIPTION': 'API for edge devices (DOMOBOI/Tuya) to push measurements and events.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

GRAPH_MODELS = {
  'app_labels': ["nilm"],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'domoboi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'nilm' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'domoboi.context_processors.google_maps_api_key',
                'domoboi.context_processors.webpush_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'domoboi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DOMOBOI_DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DOMOBOI_DB_NAME', 'domoboi'),
        'USER': os.getenv('DOMOBOI_DB_USER', 'domoboi'),
        'PASSWORD': os.getenv('DOMOBOI_DB_PASS', ''),
        'HOST': os.getenv('DOMOBOI_DB_HOST', 'localhost'),
        'PORT': os.getenv('DOMOBOI_DB_PORT', '5432'),
    },

    'development': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = False

LANGUAGES = [
    ('es', _('Spanish')),
    ('ca', _('Catalan')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/nilm/'

GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', '')

# Web Push (VAPID) — keys come from local_settings.py vars or .env fallback
VAPID_PUBLIC_KEY = os.environ.get("VAPID_PUBLIC_KEY", "")
VAPID_PRIVATE_KEY = os.environ.get("VAPID_PRIVATE_KEY", "")

# django-location-field configuration — use OpenStreetMap so no API key is required
LOCATION_FIELD = {
    'map.provider': 'openstreetmap',
    'search.provider': 'nominatim',
    'provider.openstreetmap.max_zoom': 18,
}

# Import local settings overrides if they exist (allows overriding database, DEBUG, etc.)
try:
    from .local_settings import *
except ImportError:
    pass

# Build WEBPUSH_SETTINGS after local_settings so VAPID_* vars are fully resolved
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": VAPID_PUBLIC_KEY,
    "VAPID_PRIVATE_KEY": VAPID_PRIVATE_KEY,
    "VAPID_ADMIN_EMAIL": "admin@domoboi.es",
}
